### ISSUE TITLE
Quest "Vampiro Asiatico" non si completa

### ISSUE THREAD

**Issue by Lorped** [tesivo/tesivo_s_VTMB_italian_translation_for_Unofficial_Patch#20]
https://github.com/tesivo/tesivo_s_VTMB_italian_translation_for_Unofficial_Patch/blob/7ec85391ef9a208764a8c131922d89415230751d/dlg/santa%20monica/knox.dlg#L295

In quella riga , così come nelle 296 e 297 ,  c'è una sezione tra parentesi graffe di troppo: le terza (quella con il testo in inglese).

Questo inibisce il dialogo di completamentento quest.

**Comment by tesivo** [comment]
Grazie per la segnalazione. Fixato!
